spring.application.name=promptle

spring.datasource.url=jdbc:postgresql://localhost:5432/promptle_db
spring.datasource.username=charlie
spring.datasource.password=charlie

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
