spring.application.name=promptle
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

game.timer.prompting-seconds=20
game.timer.guessing-seconds=20

image.generation.provider=comfyui
image.generation.comfyui.url=http://localhost:8188
image.generation.comfyui.workflow=comfyui-workflow-api.json
image.generation.comfyui.prompt-node-id=6
image.generation.comfyui.output-node-id=9
image.storage.provider=local
image.storage.local.path=/tmp/promptle

game.timer.generating-timeout-seconds=120
